/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.upsin.embarcaciones_poo.gui;

import java.awt.Insets;
import javax.swing.SwingConstants;

/**
 *
 * @author miguel
 */
public class VistaMain extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaMain.class.getName());

    /**
     * Creates new form VistaMain
     */
    public VistaMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEnbarcaciones = new javax.swing.JButton();
        btnRegistro = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnCargaDescarga = new javax.swing.JButton();
        btnEmpresa = new javax.swing.JButton();
        btnContRetiro = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btnContenedor = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnAlmacen = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(248, 248, 248));

        jPanel3.setBackground(new java.awt.Color(153, 204, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("© 2025 MAR AZUL EMBARCACIONES");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        jPanel4.setBackground(new java.awt.Color(248, 248, 248));

        jPanel6.setBackground(new java.awt.Color(153, 204, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("© 2025 MAR AZUL EMBARCACIONES");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("GESTOR DEL PUERTO");

        btnEnbarcaciones.setBackground(new java.awt.Color(51, 102, 255));
        btnEnbarcaciones.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEnbarcaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnEnbarcaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono-embarcacion2.png"))); // NOI18N
        btnEnbarcaciones.setText("ACTIVOS");
        btnEnbarcaciones.setAlignmentX(0.5F);
        btnEnbarcaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEnbarcaciones.setIconTextGap(1);
        btnEnbarcaciones.setInheritsPopupMenu(true);
        btnEnbarcaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEnbarcaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnbarcacionesActionPerformed(evt);
            }
        });

        btnRegistro.setBackground(new java.awt.Color(51, 102, 255));
        btnRegistro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnRegistro.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono_barco3.png"))); // NOI18N
        btnRegistro.setText("REGISTRO");
        btnRegistro.setAlignmentX(0.5F);
        btnRegistro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistro.setIconTextGap(5);
        btnRegistro.setInheritsPopupMenu(true);
        btnRegistro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistroActionPerformed(evt);
            }
        });

        btnCE.setBackground(new java.awt.Color(51, 102, 255));
        btnCE.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCE.setForeground(new java.awt.Color(255, 255, 255));
        btnCE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono_Cont_Embarcacion.png"))); // NOI18N
        btnCE.setText("CE");
        btnCE.setAlignmentX(0.5F);
        btnCE.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCE.setIconTextGap(5);
        btnCE.setInheritsPopupMenu(true);
        btnCE.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("BARCOS");

        jLabel8.setFont(new java.awt.Font("Century", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("CONTENEDORES");

        btnCargaDescarga.setBackground(new java.awt.Color(255, 153, 51));
        btnCargaDescarga.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCargaDescarga.setForeground(new java.awt.Color(255, 255, 255));
        btnCargaDescarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono_CyD.png"))); // NOI18N
        btnCargaDescarga.setText("CARGA");
        btnCargaDescarga.setAlignmentX(0.5F);
        btnCargaDescarga.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCargaDescarga.setIconTextGap(5);
        btnCargaDescarga.setInheritsPopupMenu(true);
        btnCargaDescarga.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCargaDescarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargaDescargaActionPerformed(evt);
            }
        });

        btnEmpresa.setBackground(new java.awt.Color(153, 0, 255));
        btnEmpresa.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono-empresa.png"))); // NOI18N
        btnEmpresa.setText("EMPRESA");
        btnEmpresa.setToolTipText("");
        btnEmpresa.setAlignmentX(0.5F);
        btnEmpresa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmpresa.setIconTextGap(5);
        btnEmpresa.setInheritsPopupMenu(true);
        btnEmpresa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpresaActionPerformed(evt);
            }
        });

        btnContRetiro.setBackground(new java.awt.Color(255, 153, 51));
        btnContRetiro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnContRetiro.setForeground(new java.awt.Color(255, 255, 255));
        btnContRetiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono-retiro.png"))); // NOI18N
        btnContRetiro.setText("RETIRO");
        btnContRetiro.setAlignmentX(0.5F);
        btnContRetiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContRetiro.setIconTextGap(5);
        btnContRetiro.setInheritsPopupMenu(true);
        btnContRetiro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContRetiroActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("ADMINISTRACION");

        btnContenedor.setBackground(new java.awt.Color(255, 153, 51));
        btnContenedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnContenedor.setForeground(new java.awt.Color(255, 255, 255));
        btnContenedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono-contenedor.png"))); // NOI18N
        btnContenedor.setText("CONTEN");
        btnContenedor.setToolTipText("");
        btnContenedor.setAlignmentX(0.5F);
        btnContenedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContenedor.setIconTextGap(5);
        btnContenedor.setInheritsPopupMenu(true);
        btnContenedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContenedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContenedorActionPerformed(evt);
            }
        });

        btnProducto.setBackground(new java.awt.Color(153, 51, 255));
        btnProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono-producto.png"))); // NOI18N
        btnProducto.setText("PRODUCT");
        btnProducto.setToolTipText("");
        btnProducto.setAlignmentX(0.5F);
        btnProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProducto.setIconTextGap(5);
        btnProducto.setInheritsPopupMenu(true);
        btnProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });

        btnAlmacen.setBackground(new java.awt.Color(153, 0, 255));
        btnAlmacen.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnAlmacen.setForeground(new java.awt.Color(255, 255, 255));
        btnAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono-almacen.png"))); // NOI18N
        btnAlmacen.setText("ALMACEN");
        btnAlmacen.setToolTipText("");
        btnAlmacen.setAlignmentX(0.5F);
        btnAlmacen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAlmacen.setIconTextGap(5);
        btnAlmacen.setInheritsPopupMenu(true);
        btnAlmacen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlmacenActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(153, 204, 255));

        jButton1.setBackground(new java.awt.Color(153, 204, 255));
        jButton1.setFont(new java.awt.Font("Century", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("LGO-EMPRESA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addContainerGap(1014, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jButton1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(368, 368, 368))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEnbarcaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                        .addComponent(btnContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCargaDescarga, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(26, 26, 26)
                .addComponent(btnContRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(106, 106, 106))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(176, 176, 176)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(151, 151, 151)
                .addComponent(jLabel9)
                .addGap(132, 132, 132))
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, 1232, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEnbarcaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegistro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnContRetiro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProducto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnAlmacen))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnCargaDescarga)
                                    .addComponent(btnCE)))))
                    .addComponent(btnEmpresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1238, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(756, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlmacenActionPerformed
        VistaAlmacen ventana = new VistaAlmacen(); // Instancia la vistaAlmacen
        ventana.setVisible(true);                // La muestra
        this.dispose();
    }//GEN-LAST:event_btnAlmacenActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        VistaProductos ventana = new VistaProductos(); // Instancia la vistaProducto
        ventana.setVisible(true);                // La muestra
        this.dispose();
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnContenedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContenedorActionPerformed
        VistaContenedor ventana = new VistaContenedor(); // Instancia la vistaContenedor
        ventana.setVisible(true);                // La muestra
        this.dispose();
    }//GEN-LAST:event_btnContenedorActionPerformed

    private void btnContRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContRetiroActionPerformed
        VistaRetiros ventana = new VistaRetiros(); // Instancia la vistaRetiro
        ventana.setVisible(true);                // La muestra
        this.dispose();
    }//GEN-LAST:event_btnContRetiroActionPerformed

    private void btnEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpresaActionPerformed
        VistaEmpresas ventana = new VistaEmpresas(); // Instancia la vistaEmpresa
        ventana.setVisible(true);                // La muestra
        this.dispose();
    }//GEN-LAST:event_btnEmpresaActionPerformed

    private void btnCargaDescargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargaDescargaActionPerformed
        VistaCarga ventana = new VistaCarga(); // Instancia la vistaCarga
        ventana.setVisible(true);                // La muestra
        this.dispose();
    }//GEN-LAST:event_btnCargaDescargaActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed
        VistaEmbarcacionesContenedores ventana = new VistaEmbarcacionesContenedores(); // Instancia la VistaContenedor
        ventana.setVisible(true);                // La muestra
        this.dispose();
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistroActionPerformed
        VistaBarcos ventana = new VistaBarcos(); // Instancia la VistaRegistroBarcos
        ventana.setVisible(true);                // La muestra
        this.dispose();              
    }//GEN-LAST:event_btnRegistroActionPerformed

    private void btnEnbarcacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnbarcacionesActionPerformed
        VistaEmbarcaciones ventana = new VistaEmbarcaciones(); // Instancia la vistaEmbarcaciones
        ventana.setVisible(true);                // La muestra
        this.dispose();    
    }//GEN-LAST:event_btnEnbarcacionesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VistaMain ventana = new VistaMain(); // Instancia la vistaMain
        ventana.setVisible(true);                // La muestra
        this.dispose();    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VistaMain().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlmacen;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCargaDescarga;
    private javax.swing.JButton btnContRetiro;
    private javax.swing.JButton btnContenedor;
    private javax.swing.JButton btnEmpresa;
    private javax.swing.JButton btnEnbarcaciones;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    // End of variables declaration//GEN-END:variables
}
