package com.upsin.embarcaciones_poo.gui;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class VistaMain extends javax.swing.JFrame {

     private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaMain.class.getName());
    private final VistaAlmacen vistaAlmacen;
    private final VistaBarcos vistaBarcos;
    private final VistaCarga vistaCarga;
    private final VistaContenedor vistaContenedor;
    private final VistaEmbarcaciones vistaEmbarcaciones;
    private final VistaEmbarcacionesContenedores vistaEmbarcacionesContenedores;
    private final VistaEmpresas vistaEmpresas;
    private final VistaProductos vistaProductos;
    private final VistaRetiros vistaRetiros;
    private final VistaTipoBarcos vistaTipoBarcos;


    @Autowired
    public VistaMain(
            VistaAlmacen vistaAlmacen,
            VistaBarcos vistaBarcos,
            VistaCarga vistaCarga,
            VistaContenedor vistaContenedor,
            VistaEmbarcaciones vistaEmbarcaciones,
            VistaEmbarcacionesContenedores vistaEmbarcacionesContenedores,
            VistaEmpresas vistaEmpresas,
            VistaProductos vistaProductos,
            VistaRetiros vistaRetiros,
            VistaTipoBarcos vistaTipoBarcos


    ) {
        this.vistaAlmacen = vistaAlmacen;
        this.vistaBarcos = vistaBarcos;
        this.vistaCarga = vistaCarga;
        this.vistaContenedor = vistaContenedor;
        this.vistaEmbarcaciones = vistaEmbarcaciones;
        this.vistaEmbarcacionesContenedores = vistaEmbarcacionesContenedores;
        this.vistaEmpresas = vistaEmpresas;
        this.vistaProductos = vistaProductos;
        this.vistaRetiros = vistaRetiros;
        this.vistaTipoBarcos = vistaTipoBarcos;

        // Le asignamos esta ventana como principal a cada vista que lo necesite
        this.vistaTipoBarcos.setVistaMain(this);
        this.vistaAlmacen.setVistaMain(this);
        this.vistaBarcos.setVistaMain(this);
        this.vistaCarga.setVistaMain(this);
        this.vistaContenedor.setVistaMain(this);
        this.vistaEmbarcaciones.setVistaMain(this);
        this.vistaEmbarcacionesContenedores.setVistaMain(this);
        this.vistaEmpresas.setVistaMain(this);
        this.vistaProductos.setVistaMain(this);
        this.vistaRetiros.setVistaMain(this);

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMain = new javax.swing.JLabel();
        btnLogin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnBarcos = new javax.swing.JButton();
        btnEmbarcaciones = new javax.swing.JButton();
        btnEmbarcacionContenedor = new javax.swing.JButton();
        btnContenedor = new javax.swing.JButton();
        btnRetiro = new javax.swing.JButton();
        btnCarga = new javax.swing.JButton();
        btnTipoBarco = new javax.swing.JButton();
        btnProducto = new javax.swing.JButton();
        btnEmpresa = new javax.swing.JButton();
        bntAlmacen = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));
        jPanel1.setForeground(new java.awt.Color(102, 204, 255));

        btnMain.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/LogoFInal.png"))); // NOI18N

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono_CerrarSesion.png"))); // NOI18N
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btnMain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLogin)
                .addGap(62, 62, 62))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogin)
                    .addComponent(btnMain))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Century", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GESTOR DEL PUERTO");

        btnBarcos.setBackground(new java.awt.Color(51, 153, 255));
        btnBarcos.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        btnBarcos.setForeground(new java.awt.Color(255, 255, 255));
        btnBarcos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono_barco3.png"))); // NOI18N
        btnBarcos.setText("REGISTRO");
        btnBarcos.setBorderPainted(false);
        btnBarcos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBarcos.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBarcos.addMouseListener(new java.awt.event.MouseAdapter() {
        });
        btnBarcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarcosActionPerformed(evt);
            }
        });

        btnEmbarcaciones.setBackground(new java.awt.Color(51, 153, 255));
        btnEmbarcaciones.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        btnEmbarcaciones.setForeground(new java.awt.Color(255, 255, 255));
        btnEmbarcaciones.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono-embarcacion2.png"))); // NOI18N
        btnEmbarcaciones.setText("ACTIVOS");
        btnEmbarcaciones.setBorderPainted(false);
        btnEmbarcaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmbarcaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmbarcaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmbarcacionesActionPerformed(evt);
            }
        });

        btnEmbarcacionContenedor.setBackground(new java.awt.Color(51, 153, 255));
        btnEmbarcacionContenedor.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        btnEmbarcacionContenedor.setForeground(new java.awt.Color(255, 255, 255));
        btnEmbarcacionContenedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono_Cont_Embarcacion.png"))); // NOI18N
        btnEmbarcacionContenedor.setText("CE");
        btnEmbarcacionContenedor.setBorderPainted(false);
        btnEmbarcacionContenedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmbarcacionContenedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmbarcacionContenedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmbarcacionContenedorActionPerformed(evt);
            }
        });

        btnContenedor.setBackground(new java.awt.Color(255, 153, 51));
        btnContenedor.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        btnContenedor.setForeground(new java.awt.Color(255, 255, 255));
        btnContenedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono-contenedor.png"))); // NOI18N
        btnContenedor.setText("CONTEN");
        btnContenedor.setBorderPainted(false);
        btnContenedor.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnContenedor.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnContenedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnContenedorActionPerformed(evt);
            }
        });

        btnRetiro.setBackground(new java.awt.Color(255, 153, 51));
        btnRetiro.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        btnRetiro.setForeground(new java.awt.Color(255, 255, 255));
        btnRetiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono-retiro.png"))); // NOI18N
        btnRetiro.setText("RETIRO");
        btnRetiro.setBorderPainted(false);
        btnRetiro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRetiro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetiroActionPerformed(evt);
            }
        });

        btnCarga.setBackground(new java.awt.Color(255, 153, 51));
        btnCarga.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        btnCarga.setForeground(new java.awt.Color(255, 255, 255));
        btnCarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono_CyD.png"))); // NOI18N
        btnCarga.setText("CARGA");
        btnCarga.setBorderPainted(false);
        btnCarga.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCarga.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargaActionPerformed(evt);
            }
        });

        btnTipoBarco.setBackground(new java.awt.Color(153, 0, 255));
        btnTipoBarco.setFont(new java.awt.Font("Century", 1, 15)); // NOI18N
        btnTipoBarco.setForeground(new java.awt.Color(255, 255, 255));
        btnTipoBarco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono_TipoBarco.png"))); // NOI18N
        btnTipoBarco.setText("TIPOBARCO");
        btnTipoBarco.setBorderPainted(false);
        btnTipoBarco.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTipoBarco.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTipoBarco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTipoBarcoActionPerformed(evt);
            }
        });

        btnProducto.setBackground(new java.awt.Color(153, 51, 255));
        btnProducto.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        btnProducto.setForeground(new java.awt.Color(255, 255, 255));
        btnProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono-producto.png"))); // NOI18N
        btnProducto.setText("PRODUCTO");
        btnProducto.setBorderPainted(false);
        btnProducto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProducto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductoActionPerformed(evt);
            }
        });

        btnEmpresa.setBackground(new java.awt.Color(153, 0, 255));
        btnEmpresa.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        btnEmpresa.setForeground(new java.awt.Color(255, 255, 255));
        btnEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono-empresa.png"))); // NOI18N
        btnEmpresa.setText("EMPRESA");
        btnEmpresa.setBorderPainted(false);
        btnEmpresa.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEmpresa.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpresaActionPerformed(evt);
            }
        });

        bntAlmacen.setBackground(new java.awt.Color(153, 51, 255));
        bntAlmacen.setFont(new java.awt.Font("Century", 1, 16)); // NOI18N
        bntAlmacen.setForeground(new java.awt.Color(255, 255, 255));
        bntAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icono-almacen.png"))); // NOI18N
        bntAlmacen.setText("ALMACEN");
        bntAlmacen.setBorderPainted(false);
        bntAlmacen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bntAlmacen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        bntAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntAlmacenActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel5.setText("BARCOS");

        jLabel6.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel6.setText("CONTENEDORES");

        jLabel7.setFont(new java.awt.Font("Century", 1, 18)); // NOI18N
        jLabel7.setText("ADMINISTRACION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(392, 392, 392))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBarcos, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEmbarcaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnEmbarcacionContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 133, Short.MAX_VALUE)
                .addComponent(btnContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntAlmacen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTipoBarco, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(261, 261, 261)
                .addComponent(jLabel7)
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel3)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBarcos, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEmbarcaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRetiro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEmbarcacionContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTipoBarco, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bntAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    


    private void btnBarcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarcosActionPerformed
        vistaBarcos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBarcosActionPerformed

    private void btnEmbarcacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmbarcacionesActionPerformed
        vistaEmbarcaciones.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEmbarcacionesActionPerformed

    private void btnEmbarcacionContenedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmbarcacionContenedorActionPerformed
        vistaEmbarcacionesContenedores.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEmbarcacionContenedorActionPerformed

    private void btnContenedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnContenedorActionPerformed
        vistaContenedor.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnContenedorActionPerformed

    private void btnRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetiroActionPerformed
        vistaRetiros.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRetiroActionPerformed

    private void btnCargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargaActionPerformed
        vistaCarga.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnCargaActionPerformed

    private void btnProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductoActionPerformed
        vistaProductos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnProductoActionPerformed

    private void btnEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpresaActionPerformed
        vistaEmpresas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEmpresaActionPerformed

    private void btnTipoBarcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTipoBarcoActionPerformed
        vistaTipoBarcos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnTipoBarcoActionPerformed

    private void bntAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntAlmacenActionPerformed
        vistaAlmacen.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bntAlmacenActionPerformed

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        VistaLogin login = new VistaLogin();  // Crear instancia
        login.setVisible(true);               // Mostrar nueva ventana
        this.setVisible(false);               // Ocultar la actual
    }//GEN-LAST:event_btnLoginMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntAlmacen;
    private javax.swing.JButton btnBarcos;
    private javax.swing.JButton btnCarga;
    private javax.swing.JButton btnContenedor;
    private javax.swing.JButton btnEmbarcacionContenedor;
    private javax.swing.JButton btnEmbarcaciones;
    private javax.swing.JButton btnEmpresa;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel btnMain;
    private javax.swing.JButton btnProducto;
    private javax.swing.JButton btnRetiro;
    private javax.swing.JButton btnTipoBarco;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
